runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /file
  static_dir: file

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /.*
  script: server.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]